program: train.py
method: grid
metric:
  name: val_loss
  goal: minimize
parameters:
  batch_size: 
    values: [4, 8, 16]
  block_size: 
    values: [4, 8, 16]
  max_iters:
    values: [12000]
  lr: 
    values: [0.001, 0.0001]